{% set name = "pysimplegui" %}
{% set version = "5.0.6" %}
{% set styledName = "PySimpleGUI" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ styledName }}-{{ version }}.tar.gz
  sha256: e5825520d0bda60d8f52482732e27b161699813bef579d8fd72cc7cd870d22ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - PySimpleGUI

about:
  home: https://github.com/PySimpleGUI/PySimpleGUI
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: license.txt
  summary: GUI SDK Launched in 2018 Actively developed and supported. Super-simple to create custom GUI's.  Python 2.7 & 3 Support. 100 Demo programs & Cookbook for rapid start. Extensive documentation. Examples using Machine Learning(GUI, OpenCV Integration,  Chatterbot), Rainmeter Style Floating Desktop Widgets, Matplotlib
    + Pyplot integration, add GUI to command line scripts, PDF & Image Viewer. Great for beginners as well as advanced GUI programmers
  doc_url: http://www.pysimplegui.org/
  dev_url: https://github.com/PySimpleGUI/PySimpleGUI

extra:
  recipe-maintainers:
    - mxr-conda
    - agcopenhaver
    - silun
    - rluria14
    - oblute
